export const FETCHING_QUESTIONS_REQUEST = "FETCHING_QUESTIONS_REQUEST";
export const FETCHING_QUESTIONS_SUCCESS = "FETCHING_QUESTIONS_SUCCESS";
export const FETCHING_QUESTIONS_ERROR = "FETCHING_QUESTIONS_ERROR";
export const NEXT_QUESTION = "NEXT_QUESTION";
export const CORRECT_ANSWER = "CORRECT_ANSWER";
export const USER_ANSWER = "USER_ANSWER";
export const CLEAR = "CLEAR";
